### ISSUE TITLE
netmdcli play track bug

### ISSUE THREAD

**Issue by joshuadavila** [linux-minidisc/linux-minidisc#38]
netmdcli play track bug

there is a bug on netmdcli play #track, probably affects other commands that use strtoul function too. Whenever you select a track number, it interpretes it as a hex number rather than decimal.

**Comment by thp** [comment]
According to https://github.com/glaubitz/linux-minidisc/blob/master/netmdcli/netmdcli.c#L296 it does use base 10 for converting the number:

    i = strtoul(argv[2],NULL, 10);

According to `git blame`, this line was last touched 6 years ago in commit https://github.com/glaubitz/linux-minidisc/commit/c8084d948b32a112c8975e5cd603481f2d960340

The implementation of `netmd_set_track` is here: https://github.com/lainredsonic/mod_netmd/blob/master/netmd.c#L889

Note that `netmd_set_track()` has `char track` as type, and the caller does `i & 0xffff` (with `i` being `unsigned int`), but this shouldn't affect any situations where the track number <= 255.

**Comment by joshuadavila** [comment]
I have compiled(with some warnings) the code and it plays the  wrong track when i play any track number larger than 9, i.e. if i execute the application with "netmdcli play 12" it plays track 18, could it be something related to my development environment?

**Comment by eRadiofan** [comment]
I have just run into this problem, having traced it through from platinum-md, here is the defect for that: https://github.com/gavinbenda/platinum-md/issues/33

This master version of [netmd_set_track](https://github.com/linux-minidisc/linux-minidisc/blob/master/libnetmd/playercontrol.c#L100) uses some bcd encoding function: `proper_to_bcd(track, request + 9, 2);`, which is different to what is in mod_netmd.

**Comment by thp** [comment]
Implementation in `libnetmd/utils.c`:

```
inline unsigned char proper_to_bcd_single(unsigned char value)
{
    unsigned char high, low;

    low = (value % 10) & 0xf;
    high = (((value / 10) % 10) * 0x10U) & 0xf0;

    return high | low;
}

inline unsigned char* proper_to_bcd(unsigned int value, unsigned char* target, size_t len)
{
    while (value > 0 && len > 0) {
        target[len - 1] = proper_to_bcd_single(value & 0xff);
        value /= 100;
        len--;
    }

    return target;
}
```

The code in [`mod_netmd`](https://github.com/lainredsonic/mod_netmd/blob/master/netmd.c):

```
static int netmd_set_track(struct netmd_device *mdev,char track){
	int retval=0;
	unsigned char request[]={0x00,0x18,0x50,0xff,0x01,0x00,0x00,0x00,0x00,0x00,0x00};
	int size;
	unsigned char buf[255];
	request[10]=track-1;
	retval=netmd_exch_message(mdev,request,11,buf);
	if(retval<0){
		dev_info(&mdev->udev->dev,"bad ret code,returning early");
		return 0;
	}
	size=retval;
	if(size<1){
		dev_info(&mdev->udev->dev,"Invalid size");
		return -1;
	}
	dev_info(&mdev->udev->dev,"track retval:%d,buffer:%s",size,buf);
	return 1;
}
```

**Comment by thp** [comment]
If you want, try changing this line:

```
proper_to_bcd(track, request + 9, 2);
```

To this:

```
request[10] = (track - 1) & 0xff;
```

(also try different offsets (9 and 11?) and just `track` instead of `track - 1`)

Since I'm not familiar with that part of the codebase, let it be known that you do this on your own risk, if it makes the black smoke escape from your MD unit you get to keep the pieces.

**Comment by eRadiofan** [comment]
OK, the following works:

`request[10] = track & 0xff;`

But I am somewhat worried that it might not work for all players. Clearly the code as it stands, once worked for someone's player. What uses mod_netmd?

**Comment by thp** [comment]
@eRadiofan With which device did you test it?

**Comment by eRadiofan** [comment]
Tested on Sony MZ-N520

**Comment by brabes** [comment]
FWIW I've just come across this on an AIWA AM-NX9, and the change suggested by @thp has been tested and works.
