### ISSUE TITLE
Error opening minidisc device (SONY MZ-N910 (NetMD))

### ISSUE THREAD

**Issue by poulpoulsen** [linux-minidisc/linux-minidisc#68]
hello,
after successfully compile on Fedora 32, connecting reports the above error.
Error opening minidisc device (SONY MZ-N910 (NetMD)):
Error opening netmd: Error while opening the USB device

Any ideas?
Is it possible to create logs?

Regards
Poul

**Comment by thp** [comment]
Did you follow the "plugdev" group creation instructions with the udev rules file in [README.fedora](https://github.com/linux-minidisc/linux-minidisc/blob/master/README.fedora)?

**Comment by poulpoulsen** [comment]
Yes i did.
Unfortunately today i got no errors, BUT
i do not see a device.
How could i check if it is connected?
Dolphin do not show anything.
I use KDE Plasma on Fedora 32.

Regards
Poul

**Comment by poulpoulsen** [comment]
Hello,
I successfulky recompile after some fedora updates with hope to make it work. But now again opening the device with Qhimdtransfer shows error again and afterwards disconnected. 
 
Pls can you tell me how to log the communication or how to send debug messages to you.
Regards
Poul

**Comment by thp** [comment]
Is your user still part of the "plugdev" group and have you set the permissions correctly?

**Comment by thp** [comment]
> Is your user still part of the "plugdev" group and have you set the permissions correctly?

@poulpoulsen Were you able to fix it (and if so, how, so others running into the same issue can find the answer) and/or can this issue be closed?

**Comment by poulpoulsen** [comment]
hello, you can close this ticket.
currently i do not use my minidisc player.
thank you
