### ISSUE TITLE
building on catalina 10.15.7 fails 

### ISSUE THREAD

**Issue by bernaloo** [linux-minidisc/linux-minidisc#73]
im trying to build the project from the source code, as the precompiled binaries does not start (i.e. crashes in the opening process). I fixed some errors caused by missing libraries by installing them with home-brew. 
however, there seems to be something else here: 

`qhimdmainwindow.cpp:292:43: error: use of undeclared identifier 'qVariantFromValue'
        ui->himd_devices->addItem(device, qVariantFromValue((void *)dev));
                                          ^
1 error generated.
make[1]: *** [qhimdmainwindow.o] Error 1
make: *** [sub-qhimdtransfer-make_first] Error 2`

Do you recognize the error or could maybe track it to a further missing dependency? 

to reproduce this I 

1. clone the code in to a local directory
2. qmake
3. make

Thanks so much!

**Comment by thp** [comment]
Proposed fix: https://github.com/linux-minidisc/linux-minidisc/pull/74

**Comment by bernaloo** [comment]
thanks a lot for the super fast feedback. 
inspired in your fix, I downgraded the qt version in homebrew and make it run. 
Id like however to use your fix and avoid using qt4 as currently
